services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: students
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/students"
      JWT_SECRET: "FPF_4LUN0S_SYST3M"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
